refresh_rate: 30 seconds
appenders:
  stdout:
    kind: file
    path: "log/any.log"
  apis_error:
    kind: file
    path: "log/apis_error.log"
    encoder:
      pattern: "{d} {l} {t} - {m}{n}"
root:
  level: trace
  appenders:
    - stdout
loggers:
  actix_angular_web::apis:
    level: error
    appenders:
      - apis_error